from .display import OMLEDisplay, model_repr_html, show, show_in_browser

try:
    from ._version import (
        __version__,  # generated by setuptools-scm at build time
    )
except ImportError:  # pragma: no cover - source checkout without a build
    __version__ = "0.0.0+unknown"

__all__ = ["OMLEDisplay", "show", "show_in_browser", "model_repr_html", "__version__"]
